# Uncomment the next line to define a global platform for your project

platform :ios, '13.0'

target 'FlutterNative' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Flutter',:podspec => 'Flutter/Debug/Flutter.podspec'
  # Pods for FlutterNative

  target 'FlutterNativeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FlutterNativeUITests' do
    # Pods for testing
  end

end
